version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./build/package/api.dockerfile
    container_name: api
    ports:
      - "9091:9091"
    environment:
      LISTEN_ADDRESS: '0.0.0.0:9091'
      KAFKA_BROKERS: '${HOST_IP}:19092,${HOST_IP}:29092,${HOST_IP}:39092'
      KAFKA_CLIENT_ID: 'my-client'
      KAFKA_TOPIC: 'notification'

  worker1:
    build:
      context: .
      dockerfile: ./build/package/worker.dockerfile
    container_name: worker1
    environment:
      KAFKA_BROKERS: '${HOST_IP}:19092,${HOST_IP}:29092,${HOST_IP}:39092'
      KAFKA_CLIENT_ID: 'my-client'
      KAFKA_TOPIC: 'notification'

  worker2:
    build:
      context: .
      dockerfile: ./build/package/worker.dockerfile
    container_name: worker2
    environment:
      KAFKA_BROKERS: '${HOST_IP}:19092,${HOST_IP}:29092,${HOST_IP}:39092'
      KAFKA_CLIENT_ID: 'my-client'
      KAFKA_TOPIC: 'notification'

